export const PROBLEM_TAGS = [
  "My YouTube views dropped 60% after I started posting daily",
  "TikTok growth stalled at 50K followers",
  "My Instagram reach collapsed after brand deals",
  "Should I pivot my content niche or stick it out?",
  "CPM dropped significantly on my tech channel",
  "Facing burnout after posting for 300 days straight",
  "How to monetize my 100k TikTok followers?",
  "My shorts are getting views but not subscribers",
  "Sponsorship deals dried up this quarter",
  "Discord community engagement is dying",
  "Is it worth starting a newsletter in 2024?",
  "My thumbnail CTR is below 2%",
  "Audience retention drops off in the first 30 seconds",
  "Getting copyrights strikes for using royalty free music",
  "How many videos should I post per week?",
  "Is YouTube automation still profitable?",
  "My Patreon supporters are decreasing monthly",
  "Should I use AI for my scripts or keep them human?",
  "Twitter (X) reach is non-existent for my art",
  "Instagram Reels vs TikTok for short-form growth",
  "Building a personal brand vs a faceless channel",
  "Handling negativity in the comment section",
  "Finding a reliable editor for my long-form content",
  "Starting a podcast: Video or Audio only?",
  "Affiliate marketing conversion rates are very low",
  "My Twitch sub count is stagnant for 6 months",
  "Transitioning from gaming to lifestyle content",
  "How to deal with algorithm changes on Pinterest?",
  "Is LinkedIn a viable platform for creative professionals?",
  "Creating a consistent visual identity for my brand",
  "Batching content without losing quality",
  "My newsletter open rates are below 10%",
  "Balancing a full-time job and content creation",
  "Finding my unique voice in a saturated market",
  "Should I join a Creator Network or stay independent?",
  "Managing multiple social media accounts effectively",
  "Re-engaging an inactive audience",
  "Using SEO to grow my YouTube channel",
  "Collaborating with other creators in my niche",
  "Setting up a professional home studio on a budget"
];
